version: '3.1'

services:
  db-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - /path/on/host:/var/lib/postgresql/data
    container_name: backend-db-postgres-1
